lara_django_people/urls.py
"""_____________________________________________________________________

:PROJECT: LARAsuite

*lara_django_people urls *

:details: lara_django_people urls module.
         - add app specific urls here
         - 
:authors: mark doerr <mark.doerr@uni-greifswald.de>

.. note:: -
.. todo:: -
________________________________________________________________________
"""

from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView
from django_socio_grpc.settings import grpc_settings

from . import views

# Add your {cookiecutter.project_slug}} urls here.


# !! this sets the apps namespace to be used in the template
app_name = "lara_django_people"

# companies and institutions should also be added
# the 'name' attribute is used in templates to address the url independent of the view


urlpatterns = [
    path('', views.EntitySingleTableView.as_view(), name='entity-list-root'),
    path('entities/list/', views.EntitySingleTableView.as_view(), name='entity-list'),

    path('entities/create/', views.EntityCreateView.as_view(),
         name='entity-create'),
    path('entities/update/<uuid:pk>',
         views.EntityUpdateView.as_view(), name='entity-update'),
    path('entities/delete/<uuid:pk>',
         views.EntityDeleteView.as_view(), name='entity-delete'),
    # path delete selected entities
    path('entities/delete/', views.EntityDeleteSelectedView.as_view(),
           name='entity-delete-selected'),
    path('users/list/', views.LaraUserSingleTableView.as_view(),
         name='lara-user-list'),
    path('users/create/', views.LaraUserCreateView.as_view(),
         name='lara-user-create'),
    path('users/update/<uuid:pk>', views.LaraUserUpdateView.as_view(),
         name='lara-user-update'),
    path('users/delete/<uuid:pk>', views.LaraUserDeleteView.as_view(),
         name='lara-user-delete'),

    path('entities/<uuid:pk>/', views.EntityDetailView.as_view(),
         name='entity-details'),
    path('users/<uuid:pk>/', views.LaraUserDetailView.as_view(),
         name='lara-user-details'),
    path('<uuid:pk>/', views.EntityDetailView.as_view(), name='entity-details'),
    #~ path('groups/', views.userGroups, name='user-groups'),
    path('search/', views.search_all, name='search-post'),

    #path('search-results/', views.search, name='search'),
    #path('results/', views.results, name='results'),
] 


# urlpatterns = [
#     path('', views.EntitySingleTableView.as_view(), name='entity-list-root'),
#     path('entities/list/', views.EntitySingleTableView.as_view(), name='entity-list'),
#     path('addresses/list/', views.AddressesListView.as_view(), name='address-list'),
#     path('addresses/create/', views.AddressCreateView.as_view(),
#          name='address-create'),
#     path('addresses/update/<uuid:pk>', views.AddressUpdateView.as_view(),
#          name='address-update'),
#     path('addresses/delete/<uuid:pk>', views.AddressDeleteView.as_view(),
#          name='address-delete'),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# register handlers in settings
grpc_settings.user_settings["GRPC_HANDLERS"] += [
   "lara_django_people.grpc.handlers.grpc_handlers"]

lara_django_people/templates/lara_django_people/_detail.html
{% extends 'lara_django_base/lara_base_menu.html' %}


{% block toolbar %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"> {{ section_title }} </h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <a href="{% url update_link  object.pk %}" class="btn btn-warning" role="button">Edit Item</a>

        </div>
    </div>
</div>
{% endblock %}

{% block content %}

<h1>{{ object.name_full }} ({{ object.category }})</h1>

<ul>
    <li>
        {{ object.name_full }}
    </li>
    <li>
        {{ object.name }}
    </li>
</ul>
{% endblock %}

lara_django_people/templates/lara_django_people/create_form.html
{% extends 'lara_django_base/lara_base_menu.html' %}

{% block toolbar %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"> {{ section_title }} </h1>
</div>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    {% csrf_token %}
    {% crispy form %}
</div>  


{% endblock %}

lara_django_people/templates/lara_django_people/delete_form.html
{% extends 'lara_django_base/lara_base_menu.html' %}


{% block toolbar %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2"> {{ section_title }} </h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group me-2">
      <a href="{% url delete_link  object.pk %}" class="btn btn-danger" role="button">Edit Item</a>

    </div>
  </div>
</div>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<form method="post">
  <div>
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
  </div>
</form>

{% endblock %}

lara_django_people/templates/lara_django_people/delete_selected_form.html
{% extends 'lara_django_base/lara_base_menu.html' %}


{% block toolbar %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2"> {{ section_title }} </h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group me-2">
      <!--a href="{# % url delete_selected link % #}" class="btn btn-danger" role="button">Edit Item</a-->

    </div>
  </div>
</div>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<form method="post">
  <div>
    {% csrf_token %}
    {# check, if selected rows exists, then iterate over it and display the name #}
    {% if object.selected_rows %}
    {% for row in object.selected_rows %}
    <p>{{ row }}</p>
    {% endfor %}
    {% endif %}
    <p>Are you sure you want to delete all selected objects "?</p>
    <input type="submit" value="Confirm" />
  </div>
</form>

{% endblock %}

lara_django_people/templates/lara_django_people/entity_detail.html
{% extends 'lara_django_base/lara_base_menu.html' %}

{% load static %}


{% block toolbar %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"> {{ section_title }} </h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <a href="{% url update_link  object.pk %}" class="btn btn-warning" role="button">Edit Item</a>

        </div>
    </div>
</div>
{% endblock %}

{% block content %}


<div class="container">
    <div class="card mb-6">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{% get_media_prefix %}{{ object.image }}" class="card-img-top" alt="card-image">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{% if object.title %}{{ object.title }} {% endif %} {{ object.name_full }}
                        {% if object.category %}({{ object.category }}) {% endif %}</h5>
                    <p class="card-text"> {{ object.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <p> First Name:
                            <span style="font-weight: bold;"> {{ object.name_first }} </span>
                        </p>
                    </li>
                    <li class="list-group-item">
                        <p>
                            Last Name:
                            <span style="font-weight: bold;"> {{ object.name_last }} </span>
                        </p>
                    </li>
                    <li class="list-group-item">
                        <p>
                            Nick Name:
                            <span style="font-weight: bold;"> {{ object.name_nickname }} </span>
                        </p>
                    </li>
                    <li class="list-group-item">
                        <p>
                            Acronym:
                            <span style="font-weight: bold;"> {{ object.acronym }} </span>
                        </p>
                    </li>
                </ul>
                <div class="card-body">
                    <p style="font-weight: bold;"> ORCID: <a href="{{ object.ORCID }}" class="card-link"> {{ object.ORCID }} </a> </p>   
                    <p style="font-weight: bold;"> Link: <a href="{{ object.URL }}" class="card-link"> {{ object.URL }} </a> </p>
                </div>
            </div>
        </div>
    </div>
    <div class="card mb-6">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs" role="tablist">
                <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" 
                        type="button" role="tab" aria-controls="nav-home" aria-selected="true">Home</button>
                <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" 
                        type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Profile</button>
                <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" 
                        type="button" role="tab" aria-controls="nav-contact" aria-selected="false">Contact</button>
              </div>
            </ul>
        </div>
        <div class="card-body">
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                    <table class="table table-hover">
                        <thead>
                          <tr>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for key, value in contact_dict.items %}
                          <tr>
                            <th scope="row" style="font-size: larger;">{{ key  }}</th>
                            <td>{{ value | urlize }}</td>
                            <td></td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                </div>
                <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                    <table class="table table-hover">
                        <thead>
                          <tr>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <th scope="row" style="font-size: larger;">e-mail</th>
                            <td> urlize - {{ object.email | urlize }} </td> 
                            <td></td>
                          </tr>
                          <tr>
                            <th scope="row" style="font-size: larger;">Tel.(office)</th>
                            <td>{{ object.phone_number_office }}</td>
                            <td></td>
                          </tr>
                          <tr>
                            <th scope="row" style="font-size: larger;">Tel.(lab)</th>
                            <td>{{ object.phone_number_lab }}</td>
                            <td></td>
                          </tr>
                          <tr>
                            <th scope="row" style="font-size: larger;"> Tel.(mobile)</th>
                            <td>{{ object.phone_number_mobile }}</td>
                            <td></td>
                          </tr>
                        </tbody>
                      </table>
                </div>
                <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
                    <table class="table table-hover">
                        <thead>
                          <tr>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <th scope="row" style="font-size: larger;">e-mail</th>
                            <td> <a style="font-weight: normal;" href="mailto: {{ object.email }}"> {{ object.email }}</a>  </td> 
                            <td></td>
                          </tr>
                          <tr>
                            <th scope="row" style="font-size: larger;">Tel.(office)</th>
                            <td>{{ object.phone_number_office }}</td>
                            <td></td>
                          </tr>
                          <tr>
                            <th scope="row" style="font-size: larger;">Tel.(lab)</th>
                            <td>{{ object.phone_number_lab }}</td>
                            <td></td>
                          </tr>
                          <tr>
                            <th scope="row" style="font-size: larger;"> Tel.(mobile)</th>
                            <td>{{ object.phone_number_mobile }}</td>
                            <td></td>
                          </tr>
                        </tbody>
                      </table>
                </div>
              </div>
        </div>
</div>


{% endblock %}

lara_django_people/templates/lara_django_people/extradata_detail.html
{% extends 'lara_django_base/lara_base_menu.html' %}

{% block toolbar %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"> {{ section_title }} </h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <a href="{% url update_link  object.pk %}" class="btn btn-warning" role="button">Edit Item</a>

        </div>
    </div>
</div>
{% endblock %}

{% block content %}

<h1>{{ object.name }} ({{ object.description }})</h1>

<ul>
    <li>

    </li>
    <li>

    </li>
</ul>
{% endblock %}

lara_django_people/templates/lara_django_people/larauser_detail.html
{% extends 'lara_django_base/lara_base_menu.html' %}

{% block toolbar %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"> {{ section_title }} </h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <a href="{% url update_link  object.pk %}" class="btn btn-warning" role="button">Edit Item</a>

        </div>
    </div>
</div>
{% endblock %}

{% block content %}

<h1>{{ object.entity.name_full }}</h1>

<ul>
    <li>
        first name: {{object.entity.name_first}}
    </li>
    <li>
        last name: {{object.entity.name_last}}
    </li>
</ul>
{% endblock %}

lara_django_people/templates/lara_django_people/list.html
{% extends 'lara_django_base/lara_base_menu.html' %}

{% load django_tables2 %}
{% load crispy_forms_tags %}
{% load django_bootstrap5 %}


{% block searchbar %}

<form class="d-flex" role="search" action="{% url 'lara_django_people:search-post' %}" method="POST">
    {% csrf_token %}
    <input class="form-control me-2" type="search" name="search_query" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
</form>

{% endblock %}

{% block toolbar %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
   
    <h1 class="h2"> {{ section_title }} </h1>
    {% if filter %}
    <form action="" method="get" class="form form-inline d-flex flex-wrap mb-2 mb-md-0 col-sm-1  align-items-center flex-md-nowrap ">
        {% csrf_token %}

        {% bootstrap_form filter.form layout='inline' %}
        {% bootstrap_button 'filter' layout='inline'  %}
    </form>
    {% endif %}
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
           
            <a href="{% url create_link %}" class="btn btn-warning btn-sm btn-outline-secondary" role="button">Add</a>
            {% if view.export_formats %}
            {% for format in view.export_formats %}
            <button type="button" class="btn btn-sm btn-outline-secondary">
                <a href="{% export_url format %}" >
                    download  <code>.{{ format }}</code>
                </a>
            </button>
            {% endfor %}
            {% endif %}
            <a href="{% url delete_selected_link %}" id="delete-selected" class="btn btn-danger btn-sm btn-outline-secondary" role="button">Delete</a>
        </div>
        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="sync"></span>
            Sync
        </button>
    </div>
   
   
        <!--form class="" action="" method="post">
            {% csrf_token %}
            {{form|crispy}}
        </form-->


</div>
{% endblock %}

{% load render_table from django_tables2 %}
 
{% block content%}
<div class="table-container">
    <form action="{% url delete_selected_link %}" method="get" id="delete-form">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete Selected</button>

    {% render_table table  %}
</form>
</div>

{% endblock %}

{% block scripts %}

<script>
    /*
    document.addEventListener("DOMContentLoaded", function() {
        var table = document.querySelector("#entity-table");
        var dataTable = new simpleDatatables.DataTable(table);

        // Select/Deselect all checkboxes
        var checkAllCheckbox = document.querySelector("#check-all");
        var checkboxes = table.querySelectorAll("tbody input[type=checkbox]");

        checkAllCheckbox.addEventListener("change", function() {
            checkboxes.forEach(function(checkbox) {
                checkbox.checked = checkAllCheckbox.checked;
            });
        });

        // Delete selected rows
        
        var deleteSelectedButton = document.querySelector("#delete-selected");
        deleteSelectedButton.addEventListener("click", function() {
            var selectedRows = Array.from(checkboxes).filter(function(checkbox) {
                return checkbox.checked;
            }).map(function(checkbox) {
                return checkbox.closest("tr");
            });

            /*selectedRows.forEach(function(row) {
                dataTable.row(row).remove().draw(false); 
            });
        });*/
</script>

{% endblock %}

lara_django_people/templates/lara_django_people/update_form.html
{% extends 'lara_django_base/lara_base_menu.html' %}

{% block toolbar %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"> {{ section_title }} </h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <a href="{% url delete_link  object.pk %}" class="btn btn-danger" role="button">Delete Item</a>

        </div>
    </div>
</div>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    {% csrf_token %}
    {% crispy form %}
</div> 

{% endblock %}

lara_django_people/templates/lara_django_people/user_groups_list.html
{% extends 'lara_django_base/lara_base_menu.html' %}

{% block title %}People-Groups{% endblock %}

{% block top %}
<h1> LARA Groups</h1>
<p> </p>
{% endblock %}

{% block main_content %}
{% if lara_groups_list %}
<ul>
  {% for item in lara_user_list %}
  <li><a href="{% url 'lara_django_people:lara_group_detail' item.lara_group_id %}" title={{ item.name }}> {{ item.name
      }} {{ item.description }} </a> </li>
  {% endfor %}
</ul>
{% else %}
<p>No Users groups are available.</p>
{% endif %}

{% endblock %}